#!/usr/bin/env python

import sys

from rqt_gui.main import Main

#main = Main()
#sys.exit(main.main(sys.argv, standalone='robospect_mission_commander.rqt_powerball_control_extra.PowerballGUI'))

plugin = 'MissionCommanderGUI'
#plugin = 'robospect_mission_commander.rqt_powerball_control_extra.PowerballGUI'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin))
